[tool.poetry]
name = "ansible-builder"
description = "A tool for building Ansible Execution Environments"
authors = ["Ansible, Inc. <info@ansible.com>"]

# This is a placeholder value, because poetry lacks proper support
# for any kind of dynamic versioning. We publish releases via Zuul,
# which calls `tox -e version` before building the sdist / wheel.
version = "0.0.0"

[tool.poetry.dependencies]
python = "^3.6"
pyyaml = ">=3.12.0"     # Minimum for compat for el7 and el8 packaging
requirements-parser = "^0.2.0"

[tool.poetry.scripts]
ansible-builder = 'ansible_builder.cli:run'

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.7.9"
pylint = "^2.4.4"
tox = "^3.14.5"
yamllint = "^1.20.0"
black = "^19.10b0"
pytest-xdist = "^1.34.0"
Sphinx = "^3.2.1"


[tool.black]
line-length = 100
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | docs
  | installer
  | packaging
)/
'''

[build-system]
requires = ["setuptools", "poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
